# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2216884ccc75375ae7b65ec4aeed6c046444322f9a7ff3d96b13908c0c60f6a9094029ffab27e067bdb187b5ebb424102516fb0fc667634c04245d39e0a489ef

test:
  secret_key_base: a563f19c5eee014070a1e73514af4b3761a680468d197c1637302eca264220e50c1a407e5228e25f2f79316a6ad635a72363756bf903fe96b3e7f2e3a581e8d2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
